# Generated by Django 5.2.8 on 2025-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabOrder',
            new_name='LabTestOrder',
        ),
    ]
