# Generated by Django 5.2.8 on 2025-12-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0002_rename_laborder_labtestorder'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensetransaction',
            name='consultation',
        ),
        migrations.AddField(
            model_name='dispensetransaction',
            name='prescription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_transactions', to='clinical.prescription'),
        ),
    ]
