# Generated by Django 5.2.8 on 2025-12-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_dispensetransaction_consultation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensetransaction',
            name='prescription',
        ),
    ]
