# Generated by Django 5.2.8 on 2025-12-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
        ('profiles', '0003_alter_pharmacistprofile_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabTestOrder',
            new_name='TestOrder',
        ),
        migrations.RenameModel(
            old_name='LabTestResult',
            new_name='TestResult',
        ),
        migrations.RenameModel(
            old_name='LabTest',
            new_name='Tests',
        ),
    ]
